maintainer       "Lamont Granquist"
maintainer_email "lamont@scriptkiddie.org"
license          "Apache 2.0"
description      "Manage ssh_known_hosts file properly using a definition rather than an LWRP"
long_description "Manage ssh_known_hosts file properly using a definition rather than an LWRP"
version          "1.0.18"
name             "sk_ssh_known_hosts"
